name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths: ["*.typ", "*.yml", "*.bib"]

jobs:
  Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Magic Cache
        uses: determinatesystems/magic-nix-cache-action@v3

      - name: Build
        run: nix run nixpkgs#typst -- compile main.typ cv.pdf

      - name: Tag
        run: echo "TAG=$(date +%Y.%m.%d.%H.%M.%S)" >> ${GITHUB_ENV}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          files: |
            cv.pdf
